@startuml

title __MODEL's Class Diagram__\n

  namespace ub.edu {
    namespace model {
      class ub.edu.model.Client {
          - adreca : String
          - documentIdentitat : String
          - nom : String
          - pwd : String
          - usuari : String
          + getAdreca()
          + getDocumentIdentitat()
          + getNom()
          + getPwd()
          + getUsuari()
          + setAdreca()
          + setDocumentIdentitat()
          + setNom()
          + setPwd()
          + setUsuari()
      }
    }
  }


  namespace ub.edu {
    namespace model {
      class ub.edu.model.Controller {
          + Controller()
          + validateUsuari()
      }
    }
  }


  namespace ub.edu {
    namespace model {
      class ub.edu.model.Episodi {
          - data : Date
          - descripcio : String
          - duracio : String
          - idEpisodi : int
          - idSerie : String
          - idioma : String
          - numTemporada : int
          - titol : String
          + getData()
          + getDescripcio()
          + getDuracio()
          + getIdEpisodi()
          + getIdSerie()
          + getIdioma()
          + getNumTemporada()
          + getTitol()
          + setData()
          + setDescripcio()
          + setDuracio()
          + setIdEpisodi()
          + setIdSerie()
          + setIdioma()
          + setNumTemporada()
          + setTitol()
      }
    }
  }


  namespace ub.edu {
    namespace model {
      class ub.edu.model.Serie {
          - descripcio : String
          - id : String
          - titol : String
          + getDescripcio()
          + getId()
          + getTitol()
          + setDescripcio()
          + setId()
          + setTitol()
      }
    }
  }


  namespace ub.edu {
    namespace model {
      class ub.edu.model.Temporada {
          - idSerie : String
          - numEpisodis : int
          - numTemporada : int
          + getIdSerie()
          + getNumEpisodis()
          + getNumTemporada()
          + setIdSerie()
          + setNumEpisodis()
          + setNumTemporada()
      }
    }
  }


  ub.edu.model.Controller o-- ub.edu.resources.service.AbstractFactoryData : factory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
